language: php

services:
  - mysql

env:
  global:
    - COMPOSER_ROOT_VERSION=5.0.x-dev
    - PHPSTAN_VERSION=^0.12
    - SS_BASE_URL="http://localhost/"

matrix:
  include:
    - php: 7.2
      env: DB=MYSQL RECIPE_VERSION=4.5.x-dev PHPCS_TEST=1
    - php: 7.3
      env: DB=MYSQL RECIPE_VERSION=4.x-dev PHPSTAN_TEST=1
    - php: 7.4
      env: DB=MYSQL RECIPE_VERSION=4.x-dev PHPUNIT_TEST=1

before_script:
  # Extra $PATH
  - export PATH=./vendor/bin:$PATH

  # Init PHP
  - phpenv rehash
  - phpenv config-rm xdebug.ini
  - echo 'memory_limit = 2G' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  # Install composer dependencies
  - composer validate
  - composer require --no-update silverstripe/recipe-testing:^1 silverstripe/recipe-cms:$RECIPE_VERSION
  - if [[ $PHPSTAN_TEST ]]; then composer require --no-update phpstan/phpstan:$PHPSTAN_VERSION; fi
  - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
  - if [[ $PHPCS_TEST ]]; then phpcs --ignore=tests/bootstrap-phpstan.php src/ tests/ *.php; fi
  - if [[ $PHPSTAN_TEST ]]; then phpstan analyse src/ tests/ -c "phpstan.neon" -a "tests/bootstrap-phpstan.php" --level 3; fi
  - if [[ $PHPUNIT_TEST ]]; then phpunit; fi
